// src-frontend/app/privacy/page.tsx

import Link from 'next/link';

export default function PrivacyPolicyPage() {
  return (
    <main className="min-h-screen">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div className="text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight gradient-text">
            Our Commitment to Your Sovereignty
          </h1>
          <p className="mt-4 text-xl text-text-secondary">
            Privacy isn't a feature; it's our architecture.
          </p>
        </div>

        <div className="space-y-8 text-text-secondary text-lg leading-relaxed bg-glass-dark rounded-2xl border border-border-primary p-8 md:p-10">
          <section>
            <h2 className="text-2xl font-bold text-accent-tertiary mb-4">The Engelbert Principle: You Own Your Data. Period.</h2>
            <p>
              Engelbert and its flagship application, "Wise," are designed from the ground up on the principle of **Cognitive Sovereignty**. This means that your data, your thoughts, your documents, and your insights are processed and stored exclusively on your local machine.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-text-primary mb-4">What We Don't Collect</h2>
            <p>
              Our servers never see your personal content. We do not collect, store, or have access to any of the data you create or process within the "Wise: Sovereign Edition" application. This includes:
            </p>
            <ul className="list-disc list-inside mt-4 space-y-2">
              <li>The contents of your documents (PDFs, notes, etc.).</li>
              <li>Your conversations or prompts with local AI models.</li>
              <li>The insights generated by the Insight Engine.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-text-primary mb-4">Optional Cloud Features</h2>
            <p>
              In the future, we may offer optional cloud features. These services will be strictly opt-in, using a **"Bring Your Own Key" (BYOK)** model. If you choose to use a cloud AI model (e.g., from OpenAI), you will use your own API key. Your data will be sent directly from your device to their service, under their privacy policy. We act as an orchestrator, not a middleman.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-text-primary mb-4">Website & Waitlist</h2>
            <p>
              When you visit our website or sign up for our waitlist, we collect only the essential information needed to communicate with you (your email address). We use simple, privacy-respecting analytics to understand website traffic. We will never sell your information.
            </p>
          </section>

          <div className="text-center mt-12 pt-8 border-t border-border-primary">
            <Link href="/" className="btn-secondary">
              ← Back to Vision Page
            </Link>
          </div>
        </div>
      </div>
    </main>
  );
}