// src-frontend/app/privacy/page.tsx

import Link from 'next/link';

export default function PrivacyPolicyPage() {
  return (
    <main className="min-h-screen bg-slate-900 text-white font-sans">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div className="text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight text-white">
            Our Commitment to Your Sovereignty
          </h1>
          <p className="mt-4 text-lg text-slate-400">
            Privacy isn't a feature; it's our architecture.
          </p>
        </div>

        <div className="space-y-8 text-slate-300 text-lg leading-relaxed glass-effect rounded-xl p-8">
          <section>
            <h2 className="text-2xl font-bold text-green-400 mb-4">The EngelBERT Principle: You Own Your Data. Period.</h2>
            <p>
              EngelBERT and its flagship application, "Wise," are designed from the ground up on the principle of **Cognitive Sovereignty**. This means that your data, your thoughts, your documents, and your insights are processed and stored exclusively on your local machine.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">What Information We Don't Collect</h2>
            <p>
              It's simple: we do not collect, store, or have access to any of the personal content you create or process within the "Wise: Sovereign Edition" application. This includes, but is not limited to:
            </p>
            <ul className="list-disc list-inside mt-4 space-y-2">
              <li>The contents of your documents (PDFs, notes, etc.).</li>
              <li>Your conversations or prompts with the local AI models.</li>
              <li>The insights generated by the Insight Engine.</li>
              <li>Any data related to your "Second Brain."</li>
            </ul>
            <p className="mt-4">
              Our servers never see this data. It never leaves your device.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">Optional Cloud Features</h2>
            <p>
              In the future, we may offer optional "Wise Cloud" features. These services will be strictly opt-in. Our model is to allow you to **"Bring Your Own Key" (BYOK)**. This means if you choose to use a cloud-based AI model (like one from OpenAI or Anthropic), you will use your own API key. Your data will be sent directly from your device to their service, under their privacy policy. We will act as an orchestrator, not a middleman, and will not log or store this data.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">Website & Waitlist</h2>
            <p>
              When you visit our website or sign up for our waitlist via Tally.so, we collect only the essential information needed to communicate with you (your email address). We use simple, privacy-respecting analytics to understand website traffic. We will never sell your information.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">Our Promise</h2>
            <p>
              Our business model is not built on monetizing your data. It is built on providing you with a tool so valuable that you may one day choose to pay for advanced features. Your privacy is the foundation of our product, not an afterthought.
            </p>
          </section>

          <div className="text-center mt-12 pt-8 border-t border-slate-700">
            <Link href="/" className="text-blue-400 hover:text-blue-300">
              ← Back to Vision Page
            </Link>
          </div>
        </div>
      </div>
    </main>
  );
}